import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

shell = "/bin/bash"

[window]

opacity = 0.9

[font]

normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font Mono", style = "Bold Italic" }

size = 8
